### ISSUE TITLE
t posing animations

### ISSUE THREAD

**Issue by WolfHack08** [Metastruct/outfitter#25]
when i jump or reload or do something, the playermodel flickers while t-posing. any help?

**Comment by LittleSDY** [comment]
Same here,  still looking for causes.

**Comment by JosiahGoeman** [comment]
Also happening here.  Only in singleplayer mode.  All other addons disabled.  Happens on all playermodels.  Head jitters up and down while t-posing.  Happens when attacking, landing after a jump, and reloading.  Walking, sprinting, noclipping, driving cars, using the entity drive system ("mind powers" animation), and using act animations all work fine.  I'm running the Linux version of gmod.

**Comment by Python1320** [comment]
Singleplayer is not supported, just subscribe to the addons in that case? Listen server should work though (set maxplayers above 1)
