### ISSUE TITLE
0 IQ System

### ISSUE THREAD

**Issue by French-Croco** [Metastruct/outfitter#65]
The problem is that Outfiter broke for me and it downloads PMs instead of Giving it and sending outfit to others

**Comment by Cynosphere** [comment]
What I can gather through the gramatical mistakes is this is most likely Steam workshop downloads getting stuck. This is usually due to an addon elsewhere being stuck either due to it being banned or privated or some other mysterious I/O errors.

Only workarounds are to either go into the Downloads tab of Steam and spam the queue download button until everything is mounted or to close Steam entirely and delete appworkshop_4000.acf and content/4000 in steamapps/workshop.

Other than that, it is unfixable on our end.

**Comment by Earu** [comment]
The download button on the steam page used to mount the playermodel in-game this is no longer the case, now you have to click on the button located at the top right corner of your outfitter window. Using the subscribe steam button will only indeed download your outfit.
